import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({
  baseUrl: "https://musicfun.it-incubator.app/api/1.0/",
  headers: {
    "api-key": "c5979a0f-1886-4e63-9bc2-3546b075c045",
  },
});
