import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

const authMiddleware: Middleware = {
  onRequest({ request }) {
    const accessToken = localStorage.getItem("musicfun-access-token");

    if (accessToken) {
      request.headers.set("Authorization", `Bearer ${accessToken}`);
    }
    return request;
  },
  onResponse({ response }) {
    if (!response.ok) {
      // Will produce error messages like "https://example.org/api/v1/example: 404 Not Found".
      throw new Error(
        `${response.url}: ${response.status} ${response.statusText}`
      );
    }
  },
  // async onResponse({ request, response, options }) {
  //   const { body, ...resOptions } = response;
  //   // change status of response
  //   return new Response(body, { ...resOptions, status: 200 });
  // },
  // async onError({ error }) {
  //   // wrap errors thrown by fetch
  //   onError({ error }) {
  //     return new Error("Oops, fetch failed", { cause: error });
  //   },
  // },
};

export const client = createClient<paths>({
  baseUrl: "https://musicfun.it-incubator.app/api/1.0/",
  headers: {
    "api-key": "c5979a0f-1886-4e63-9bc2-3546b075c045",
  },
});

client.use(authMiddleware);
